# ----------------------------------
# request of service
# ----------------------------------
string data
---
# ----------------------------------
# response of service
# ----------------------------------
bool success
string data